{
    "extends": ["plugin:@typescript-eslint/recommended"],
    "env": { "es6": true },
    "parserOptions": { "sourceType": "module" },
    "rules":
        { 
            "semi": "error",
            "no-duplicate-imports": "error" ,
            "@typescript-eslint/no-empty-function": "off"
        },
}
